version: '3.9'

services:
  node-email-service-util:
    container_name: node-email-service-util
    build:
      context: .
    restart: unless-stopped
    ports:
      - '4275:4000'
    env_file:
      - .env
